environment/hw-rails-wordguesser-master/config/routes.rb
Rails.application.routes.draw do

  get  'new'    => 'game#new',   :as => 'new_game'
  post 'create' => 'game#create',:as => 'create_game'
  get  'show'   => 'game#show',  :as => 'game'
  post 'guess'  => 'game#guess', :as => 'guess'
  get  'win'    => 'game#win',   :as => 'win_game'
  get  'lose'   => 'game#lose',  :as => 'lose_game'

  root 'game#new'

end

environment/hw-rails-wordguesser-master/app/models/word_guesser_game.rb
class WordGuesserGame

  attr_accessor :word, :guesses, :wrong_guesses

  def initialize(word)
    @word = word
    @guesses = ''
    @wrong_guesses = ''
  end

  def guess(letter)
    if letter.nil? || letter !~ /\A[a-zA-Z]\Z/i # match single letter,ignoring case
      raise ArgumentError
    end
    letter = letter[0].downcase
    if  @word.include?(letter) && !@guesses.include?(letter)
      @guesses += letter
    elsif !@word.include?(letter) && !@wrong_guesses.include?(letter)
      @wrong_guesses += letter
    else
      false
    end
  end

  def word_with_guesses
    @word.gsub(/./)  { |letter| @guesses.include?(letter) ? letter : '-' }
  end

  def check_win_or_lose
    return :play if @word.blank?

    if word_with_guesses == @word
      :win
    elsif @wrong_guesses.length > 6
      :lose
    else
      :play
    end
  end

  # Get a word from remote "random word" service

  def self.get_random_word
    require 'uri'
    require 'net/http'
    uri = URI('http://randomword.saasbook.info/RandomWord')
    Net::HTTP.post_form(uri ,{}).body
  end

end

environment/hw-rails-wordguesser-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

environment/hw-rails-wordguesser-master/app/controllers/game_controller.rb
class GameController < ApplicationController

  before_action :get_game_from_session
  after_action  :store_game_in_session
  
  def new
  end

  def create
    word = params[:word] || WordGuesserGame.get_random_word
    @game = WordGuesserGame.new(word)
    redirect_to game_path
  end

  def show
    status = @game.check_win_or_lose
    redirect_to win_game_path if status == :win
    redirect_to lose_game_path if status == :lose
  end

  def guess
    letter = params[:guess]
    begin
      if ! @game.guess(letter[0])
        flash[:message] = "You have already used that letter." 
      end
    rescue ArgumentError
      flash[:message] = "Invalid guess."
    end
    redirect_to game_path
  end

  def win
    redirect_to game_path unless @game.check_win_or_lose == :win
  end
  
  def lose
    redirect_to game_path unless @game.check_win_or_lose == :lose
  end

  private
  
  def get_game_from_session
    @game = WordGuesserGame.new('')
    if !session[:game].blank?
      @game = YAML.load(session[:game])
    end
  end

  def store_game_in_session
    session[:game] = @game.to_yaml
  end
end

environment/hw-rails-wordguesser-master/app/views/game/lose.html.erb
<h1>Sorry, you lose!</h1>


<div class="alert alert-danger">
   The word was:
   <span class="strong"><%= @game.word %></span>
</div>

<%= render :template => 'game/new' %>

environment/hw-rails-wordguesser-master/app/views/game/new.html.erb
<%= form_tag create_game_path, :method => :post do %>
  <div class="form-row py-3 border-top">
    <%= submit_tag 'New Game', :class => "col-md-2 offset-md-5 btn btn-primary form-control" %>
  </div>
<% end %>

environment/hw-rails-wordguesser-master/app/views/game/show.html.erb
<% if flash[:message] %>
   <div class="alert alert-danger">
     <span class="error"><%= flash[:message] %></span>
   </div>
<% end %>

<div class="alert alert-warning">
  <p class="lead">
    Wrong Guesses:
    <span class="guesses"><%= @game.wrong_guesses %></span>
  </p>
</div>

<p class="alert alert-success">
  Word so far:
  <span class="word"><%= @game.word_with_guesses %></span>
</p>

<%= form_tag guess_path, :method => 'post' do %>
  <div class="form-group row">
    <label for="guess" class="col-md-2 col-form-label">Guess a letter:</label>
    <input type="text" name="guess" autocomplete="off"
           class="form-control col-md-1"/>
    <input type="submit" value="Guess!" class="col-md-2 btn btn-success"/>
  </div>
<% end %>

<%= render :template => 'game/new' %>

environment/hw-rails-wordguesser-master/app/views/game/win.html.erb
<h1>You Win!</h1>

<div class="alert alert-success">
  The word was
  <span class="win"><%= @game.word %></span>.
</div>

<%= render :template => 'game/new' %>

environment/hw-rails-wordguesser-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WordGuesser</title>
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="jumbotron">
      <h1 class="display-4">Play WordGuesser!</h1>
      <p class="lead">Random word generator provided by Watchout4snakes.com</p>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>